### ISSUE TITLE
Freezes Loadup

### ISSUE THREAD

**Issue by CFlatFlat** [Treppord/PSWG-Adventures-EP1#2]
Version 0.0.24.1 freezes the loading screen when trying to play it with the newest version of the main mod, 0.0.116. It gives the following error in the console:

	at com.parzivail.p3d.P3dModel.read(P3dModel.java:287) ~[pswg-0.0.116+1.20.2.jar:?]
	at com.parzivail.p3d.P3dManager.readResource(P3dManager.java:32) ~[pswg-0.0.116+1.20.2.jar:?]
	at com.parzivail.util.data.KeyedReloadableLoader.prepare(KeyedReloadableLoader.java:68) ~[pswg-0.0.116+1.20.2.jar:?]
	at com.parzivail.util.data.KeyedReloadableLoader.lambda$reload$0(KeyedReloadableLoader.java:42) ~[pswg-0.0.116+1.20.2.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[15:02:29] [Worker-Main-9/WARN]: Texture pswg-adventures:item/jedi_mask with size 8x8 limits mip level from 4 to 3
[15:02:29] [Worker-Main-9/WARN]: minecraft:textures/atlas/blocks.png: dropping miplevel from 4 to 3, because of minimum power of two: 8
[15:02:29] [Worker-Main-4/ERROR]: Couldn't parse data file pswg-adventures:ship/zephyr_j from pswg-adventures:models/ship/zephyr_j.p3d
java.io.IOException: Input file not P3D model
	at com.parzivail.p3d.P3dModel.read(P3dModel.java:287) ~[pswg-0.0.116+1.20.2.jar:?]
	at com.parzivail.p3d.P3dManager.readResource(P3dManager.java:32) ~[pswg-0.0.116+1.20.2.jar:?]
	at com.parzivail.util.data.KeyedReloadableLoader.prepare(KeyedReloadableLoader.java:68) ~[pswg-0.0.116+1.20.2.jar:?]
	at com.parzivail.util.data.KeyedReloadableLoader.lambda$reload$0(KeyedReloadableLoader.java:42) ~[pswg-0.0.116+1.20.2.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[15:02:30] [Worker-Main-7/WARN]: Exception loading blockstate definition: 'pswg-adventures:blockstates/merchant_station.json' in resourcepack: 'fabric' for variant: 'facing=east': Unknown blockstate property: 'facing'
[15:02:30] [Worker-Main-7/WARN]: Exception loading blockstate definition: 'pswg-adventures:blockstates/merchant_station.json' in resourcepack: 'fabric' for variant: 'facing=south': Unknown blockstate property: 'facing'
[15:02:30] [Worker-Main-7/WARN]: Exception loading blockstate definition: 'pswg-adventures:blockstates/merchant_station.json' in resourcepack: 'fabric' for variant: 'facing=north': Unknown blockstate property: 'facing'
[15:02:30] [Worker-Main-7/WARN]: Exception loading blockstate definition: 'pswg-adventures:blockstates/merchant_station.json' in resourcepack: 'fabric' for variant: 'facing=west': Unknown blockstate property: 'facing'
[15:02:30] [Worker-Main-7/WARN]: Exception loading blockstate definition: 'pswg-adventures:blockstates/merchant_station.json' missing model for variant: 'pswg-adventures:merchant_station#'
[15:02:30] [Worker-Main-7/WARN]: Unable to load model: 'pswg-adventures:alloygery_tab_item#inventory' referenced from: pswg-adventures:alloygery_tab_item#inventory: java.io.FileNotFoundException: pswg-adventures:models/item/alloygery_tab_item.json

**Comment by reverentfeynmen** [comment]
Is that the fabric or mod version?

**Comment by reverentfeynmen** [comment]
It's all versions! not that version.

**Comment by reverentfeynmen** [comment]
What version of Windows do you have? This was not happening to me until I got Windows 11. Windows 11 ruins everything.

**Comment by reverentfeynmen** [comment]
Any information on how to fix?

**Comment by reverentfeynmen** [comment]
Only in 1.20.

**Comment by ghost** [comment]
Please give this guy attention.

**Comment by CFlatFlat** [comment]
Deleting comments is bad practice since it makes it more difficult for others to follow and participate. The issue has nothing to do with Windows version, and I am on W10.

The mod does not to be given much care by the developer, given the completely lack of attention this fatal issue has gotten and the fact that the author did not even check if the mod ran before uploading this file. I suggest ignoring this mod since it is very likely to not be very good anyway, at least given the indicators I'm seeing.

**Comment by ghost** [comment]
> Deleting comments is bad practice since it makes it more difficult for others to follow and participate. The issue has nothing to do with Windows version, and I am on W10.
> 
> The mod does not to be given much care by the developer, given the completely lack of attention this fatal issue has gotten and the fact that the author did not even check if the mod ran before uploading this file. I suggest ignoring this mod since it is very likely to not be very good anyway, at least given the indicators I'm seeing.

No it's a great mod. It adds Mandalorian armor and more planets. Don't ignore it please. If it can't be fixed, can you tell the creator to add Mandalorian armor to the mod?

**Comment by ghost** [comment]
> Deleting comments is bad practice since it makes it more difficult for others to follow and participate. The issue has nothing to do with Windows version, and I am on W10.
> 
> The mod does not to be given much care by the developer, given the completely lack of attention this fatal issue has gotten and the fact that the author did not even check if the mod ran before uploading this file. I suggest ignoring this mod since it is very likely to not be very good anyway, at least given the indicators I'm seeing.

This was not happening the last time I used it for 1.20.2, How did it just happened all of a sudden?

**Comment by NyraHimeshima** [comment]
Hi, i get this issue too, i fixed it by replacing all the files .nem in assets/pswg-adventures/models/armor with the clonetrooper.nem from "PSWG Addon: Clone Wars" (C/C all and rename the exact same way)

U'll get glitchy armor for all Mando/Vader/Jedi armor, but the mod works and u can play it without crash/launch issue.

To fix it completely u need to recreate the .bbmodel for all the bugged armors (too long to do for me, don't have this much time) and recreate a clean .nem (u can take the one from "PSWG Addon: Clone Wars" as base)

Hope it helps, even 1y later.

(Created this account just for that message)

**Comment by ghost** [comment]
I will try thank you.
